# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: controllers_initial_group_
  joint_model_group_pose: controllers_initial_pose_
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - virtual_joint1
    - LHY
    - LHR
    - LHP
    - LKP
    - LAP
    - LAR
    - RHY
    - RHR
    - RHP
    - RKP
    - RAP
    - RAR
    - TSY
    - LSP
    - LSR
    - LSY
    - LEP
    - LWY
    - LWP
    - LWR
    - LF11
    - LF12
    - LF13
    - LF21
    - LF22
    - LF23
    - LF31
    - LF32
    - LF33
    - NKY
    - NK1
    - NK2
    - RSP
    - RSR
    - RSY
    - REP
    - RWY
    - RWP
    - RWR
    - RF11
    - RF12
    - RF13
    - RF21
    - RF22
    - RF23
    - RF31
    - RF32
    - RF33
    - RF41
    - RF42
    - RF43
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
drchubo:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  left_arm_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - LSP
      - LSR
      - LSY
      - LEP
      - LWY
      - LWP
    gains:
      LSP: { p: 10, i: 1, d: 0.1, i_clamp: 1}
      LSR: { p: 10, i: 1, d: 0.1, i_clamp: 1}
      LSY: { p: 10, i: 1, d: 0.1, i_clamp: 1}
      LEP: { p: 10, i: 1, d: 0.1, i_clamp: 1}
      LWY: { p: 10, i: 1, d: 0.1, i_clamp: 1}
      LWP: { p: 10, i: 1, d: 0.1, i_clamp: 1}
  left_hand_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - LWR
      - LF11
      - LF12
      - LF13
      - LF21
      - LF22
      - LF23
      - LF31
      - LF32
      - LF33
    gains:
      LWR: { p: 0.1, i: 0.01, d: 0.001, i_clamp: 0.1}
      LF11: { p: 0.1, i: 0.01, d: 0.001, i_clamp: 0.1}
      LF12: { p: 0.1, i: 0.01, d: 0.001, i_clamp: 0.1}
      LF13: { p: 0.1, i: 0.01, d: 0.001, i_clamp: 0.1}
      LF21: { p: 0.1, i: 0.01, d: 0.001, i_clamp: 0.1}
      LF22: { p: 0.1, i: 0.01, d: 0.001, i_clamp: 0.1}
      LF23: { p: 0.1, i: 0.01, d: 0.001, i_clamp: 0.1}
      LF31: { p: 0.1, i: 0.01, d: 0.001, i_clamp: 0.1}
      LF32: { p: 0.1, i: 0.01, d: 0.001, i_clamp: 0.1}
      LF33: { p: 0.1, i: 0.01, d: 0.001, i_clamp: 0.1}
  right_arm_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - RSP
      - RSR
      - RSY
      - REP
      - RWY
      - RWP
    gains:
      RSP: { p: 10, i: 1, d: 0.1, i_clamp: 1}
      RSR: { p: 10, i: 1, d: 0.1, i_clamp: 1}
      RSY: { p: 10, i: 1, d: 0.1, i_clamp: 1}
      REP: { p: 10, i: 1, d: 0.1, i_clamp: 1}
      RWY: { p: 10, i: 1, d: 0.1, i_clamp: 1}
      RWP: { p: 10, i: 1, d: 0.1, i_clamp: 1}
  right_hand_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - RWR
      - RF11
      - RF12
      - RF13
      - RF21
      - RF22
      - RF23
      - RF31
      - RF32
      - RF33
      - RF41
      - RF42
      - RF43
    gains:
      RWR: { p: 0.1, i: 0.01, d: 0.001, i_clamp: 0.1}
      RF11: { p: 0.1, i: 0.01, d: 0.001, i_clamp: 0.1}
      RF12: { p: 0.1, i: 0.01, d: 0.001, i_clamp: 0.1}
      RF13: { p: 0.1, i: 0.01, d: 0.001, i_clamp: 0.1}
      RF21: { p: 0.1, i: 0.01, d: 0.001, i_clamp: 0.1}
      RF22: { p: 0.1, i: 0.01, d: 0.001, i_clamp: 0.1}
      RF23: { p: 0.1, i: 0.01, d: 0.001, i_clamp: 0.1}
      RF31: { p: 0.1, i: 0.01, d: 0.001, i_clamp: 0.1}
      RF32: { p: 0.1, i: 0.01, d: 0.001, i_clamp: 0.1}
      RF33: { p: 0.1, i: 0.01, d: 0.001, i_clamp: 0.1}
      RF41: { p: 0.1, i: 0.01, d: 0.001, i_clamp: 0.1}
      RF42: { p: 0.1, i: 0.01, d: 0.001, i_clamp: 0.1}
      RF43: { p: 0.1, i: 0.01, d: 0.001, i_clamp: 0.1}
  torso_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - TSY
    gains:
      TSY: { p: 10, i: 1, d: 0.1, i_clamp: 1}
  head_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - NKY
      - NK1
      - NK2
    gains:
      NKY: { p: 0.1, i: 0.01, d: 0.001, i_clamp: 0.1}
      NK1: { p: 0.1, i: 0.01, d: 0.001, i_clamp: 0.1}
      NK2: { p: 0.1, i: 0.01, d: 0.001, i_clamp: 0.1}
  left_leg_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - LHY
      - LHR
      - LHP
      - LKP
      - LAP
      - LAR    
    gains:
      LHY: { p: 10, i: 1, d: 0.1, i_clamp: 1}
      LHR: { p: 10, i: 1, d: 0.1, i_clamp: 1}
      LHP: { p: 10, i: 1, d: 0.1, i_clamp: 1}
      LKP: { p: 10, i: 1, d: 0.1, i_clamp: 1}
      LAP: { p: 10, i: 1, d: 0.1, i_clamp: 1}
      LAR: { p: 10, i: 1, d: 0.1, i_clamp: 1}
  right_leg_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - RHY
      - RHR
      - RHP
      - RKP
      - RAP
      - RAR
    gains:
      RHY: { p: 10, i: 1, d: 0.1, i_clamp: 1}
      RHR: { p: 10, i: 1, d: 0.1, i_clamp: 1}
      RHP: { p: 10, i: 1, d: 0.1, i_clamp: 1}
      RKP: { p: 10, i: 1, d: 0.1, i_clamp: 1}
      RAP: { p: 10, i: 1, d: 0.1, i_clamp: 1}
      RAR: { p: 10, i: 1, d: 0.1, i_clamp: 1}

controller_list:
  - name: drchubo/left_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - LSP
      - LSR
      - LSY
      - LEP
      - LWY
      - LWP
  - name: drchubo/left_hand_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - LWR
      - LF11
      - LF12
      - LF13
      - LF21
      - LF22
      - LF23
      - LF31
      - LF32
      - LF33
  - name: drchubo/right_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - RSP
      - RSR
      - RSY
      - REP
      - RWY
      - RWP
  - name: drchubo/right_hand_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - RWR
      - RF11
      - RF12
      - RF13
      - RF21
      - RF22
      - RF23
      - RF31
      - RF32
      - RF33
      - RF41
      - RF42
      - RF43
  - name: drchubo/torso_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - TSY
  - name: drchubo/head_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - NKY
      - NK1
      - NK2
  - name: drchubo/left_leg_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - LHY
      - LHR
      - LHP
      - LKP
      - LAP
      - LAR
  - name: drchubo/right_leg_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - RHY
      - RHR
      - RHP
      - RKP
      - RAP
      - RAR
